# Generated by Django 5.2.7 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('medicamento', 'Medicamento'), ('cita', 'Cita médica'), ('almuerzo', 'Almuerzo'), ('paseo', 'Paseo'), ('cena', 'Cena')], max_length=32)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('notas', models.TextField(blank=True)),
                ('frecuencia', models.CharField(choices=[('una_vez', 'Una vez'), ('diario', 'Diario'), ('semanal', 'Semanal')], default='una_vez', max_length=20)),
                ('alarma', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
